package services;

import models.Patient;
import models.VitalSign;

import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class CertificateService {

    public static String generateDeathCertificate(Patient patient, String doctorName, String doctorId,
                                                  String dateTimeOfDeath, String cause, String summary,
                                                  String notes, String signature) throws Exception {
        return generateDeathCertificate(patient, doctorName, doctorId, dateTimeOfDeath, cause, summary, notes, signature, "");
    }

    public static String generateDeathCertificate(Patient patient, String doctorName, String doctorId,
                                                  String dateTimeOfDeath, String cause, String summary,
                                                  String notes, String signature, String signatureImagePath) throws Exception {
        File folder = new File("data/generated/death-certificates");
        folder.mkdirs();

        String certificateNumber = patient.getDeathCertificateNumber();
        if (certificateNumber == null || certificateNumber.isBlank()) {
            certificateNumber = "DC-" + patient.getPatientId() + "-" + System.currentTimeMillis();
        }

        File file = new File(folder, certificateNumber + ".pdf");

        String generatedAt = now();
        ArrayList<String> lines = new ArrayList<>();
        lines.add("Hospital/System: Smart Patient Monitoring System");
        lines.add("Certificate Type: Death Certificate");
        lines.add("Certificate Number: " + certificateNumber);
        lines.add("Patient ID: " + patient.getPatientId());
        lines.add("Patient Full Name: " + patient.getName());
        lines.add("Date of Birth: " + patient.getBirthDate());
        lines.add("Section and Room: " + patient.getSection() + " / " + patient.getRoom());
        lines.add("Date and Time of Death: " + dateTimeOfDeath);
        lines.add("Cause of Death: " + cause);
        lines.add("Clinical Summary: " + summary);
        lines.add("Last Known Vitals: " + formatVitals(patient.getVitalSign()));
        lines.add("Pronouncing Doctor: " + doctorName + " / ID: " + doctorId);
        lines.add("Doctor Notes: " + notes);
        lines.add("Signature: " + signature);
        lines.add("Signature Image: " + (signatureImagePath == null || signatureImagePath.isBlank() ? "Not imported" : signatureImagePath));
        lines.add("Generated Date/Time: " + generatedAt);
        lines.add("Disclaimer: Generated by Smart Patient Monitoring System for project/demo use.");

        PdfCertificateWriter.writeCertificate(file, "Smart Patient Monitoring System", lines, signatureImagePath);
        patient.setDeathCertificateNumber(certificateNumber);
        return file.getPath();
    }

    public static String generateBirthCertificate(String babyName, String motherId, String parentInfo,
                                                  String birthDateTime, String gender, String birthWeight,
                                                  String deliveryType, String staffName, String staffId,
                                                  String notes, String signature) throws Exception {
        return generateBirthCertificate(babyName, motherId, "", "", "", "", parentInfo, birthDateTime,
                gender, birthWeight, deliveryType, staffName, staffId, notes, signature, "");
    }

    public static String generateBirthCertificate(String babyName, String motherId, String motherFirstName,
                                                  String motherLastName, String fatherFirstName,
                                                  String fatherLastName, String parentInfo,
                                                  String birthDateTime, String gender, String birthWeight,
                                                  String deliveryType, String staffName, String staffId,
                                                  String notes, String signature, String signatureImagePath) throws Exception {
        File folder = new File("data/generated/birth-certificates");
        folder.mkdirs();

        String safeName = babyName == null || babyName.isBlank() ? "newborn" : babyName.replaceAll("[^a-zA-Z0-9_-]", "_");
        String certificateNumber = "BC-" + safeName + "-" + System.currentTimeMillis();
        File file = new File(folder, certificateNumber + ".pdf");

        String generatedAt = now();
        ArrayList<String> lines = new ArrayList<>();
        lines.add("Hospital/System: Smart Patient Monitoring System");
        lines.add("Certificate Type: Birth Certificate");
        lines.add("Certificate Number: " + certificateNumber);
        lines.add("Newborn Name: " + babyName);
        lines.add("Mother ID: " + motherId);
        lines.add("Mother Name: " + motherFirstName + " " + motherLastName);
        lines.add("Father Name: " + fatherFirstName + " " + fatherLastName);
        lines.add("Parent Contact Info: " + parentInfo);
        lines.add("Date and Time of Birth: " + birthDateTime);
        lines.add("Gender: " + gender);
        lines.add("Birth Weight: " + birthWeight);
        lines.add("Delivery Type: " + deliveryType);
        lines.add("Doctor/Nurse Name and ID: " + staffName + " / " + staffId);
        lines.add("Notes: " + notes);
        lines.add("Signature: " + signature);
        lines.add("Signature Image: " + (signatureImagePath == null || signatureImagePath.isBlank() ? "Not imported" : signatureImagePath));
        lines.add("Generated Date/Time: " + generatedAt);
        lines.add("Disclaimer: Generated by Smart Patient Monitoring System for project/demo use.");

        PdfCertificateWriter.writeCertificate(file, "Smart Patient Monitoring System", lines, signatureImagePath);
        return file.getPath();
    }

    private static String formatVitals(VitalSign vitalSign) {
        if (vitalSign == null) {
            return "No vitals recorded";
        }
        return String.format("%.1f C, HR %d bpm, BP %d/%d mmHg, SpO2 %d%%",
                vitalSign.getTemperature(),
                vitalSign.getHeartRate(),
                vitalSign.getSystolicPressure(),
                vitalSign.getDiastolicPressure(),
                vitalSign.getOxygenLevel());
    }

    private static String now() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));
    }
}
